---
title: "Gayathri Penmatcha"
---

# About Me
::: {.aboutme}
• Results-driven professional with 3+ years of experience in business analysis, operations management, and customer service, skilled in optimizing procurement workflows, managing vendor relationships, and leading teams to improve operational efficiency by up to 15%.   
• Proficient in data analysis and reporting using SQL, Excel, Tableau, Python, and enterprise tools like JIRA and ServiceNow,with a proven ability to translate complex data into actionable insights that enhance customer satisfaction and business performance.   
• Currently pursuing an MBA focused on strategy and project management, combining strong leadership, communication, and problem-solving skills to contribute effectively to sales, procurement, account management, and operations leadership roles.  
:::

# Education

**Master of Business Administration**   
University Canada West | *2024 - Present*

**Bachelors of Computer Science and Technology**   
Sagi Ramakrsihnam Raju Engineering | *2018 - 2022*

# Experience

**Client Advisor** 
Australian Boot Company | *September 2024 - Present*.  
- Managed online and in-store customer orders, ensuring accurate fulfillment and smooth coordination between inventory and sales teams.   
- Delivered personalized product recommendations, improving customer satisfaction and contributing to a 15–20% increase in repeat business.   

**Business Analyst** 
Saptharishi Solutions | *October 2022 - Jan 2024*.  
- Analyzed procurement and workflow processes to identify inefficiencies, leading to a 15% improvement in operational efficiency.   
- Created dashboards and reports that supported data-driven decisions, enhancing customer satisfaction and business performance.   

**Programmer Analyst Trainee** 
Cognizant | *February 2022 - September 2022*.  
- Contributed to the development and maintenance of enterprise systems, enhancing internal workflow efficiency and interdepartmental data accuracy.   
- Collaborated with cross-functional teams to gather requirements and deliver system enhancements, showcasing adaptability and problem-solving under tight timelines.   

**Operations Manager** 
Indian Oil Corporation | *January 2020 - August 2022*.  
- Led a team of 10 to optimize fuel inventory management and vendor scheduling, reducing stock shortages by 15% and improving operational flow.   
- Resolved customer issues promptly while mentoring staff, boosting customer satisfaction scores and increasing repeat
business by 20%.

# Technical Skills
- Productivity & Visualization: Microsoft office Suite (Excel, Word, Outlook)   
- ERP Software: SAP   
- Data Analysis & Collaboration: Tableau, Microsoft Excel, SharePoint.  
- Project & Issue Tracking Tools JIRA, Confluence, ServiceNow.  
- Microsoft Office Platforms: Amazon AWS, EC2, Hadoop, Google Collab.  
- Languages & Databases: Python, Java, MYSQL.  
- Libraries: NumPy, Pandas, Matplotlib.  
- Environment: JupyterNotebook , PyCharm, MATLAB.  




To Know more about myself visit my Linkedin Profile <www.linkedin.com/in  gayathri-penmatcha-588151349>
